version: "3.3"
services: 
  murmur:
    image: ghcr.io/ekremparlak/murmur:1.3
    restart: unless-stopped
    volumes: 
      - murmur_data:/var/lib/murmur
    ports:
      - 64738:64738/udp
      - 64738:64738/tcp
      - 50051:50051/tcp
  mumble-web:
    image: ghcr.io/ekremparlak/mumble-web
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:80
  mumble-web-proxy:
    image: ghcr.io/ekremparlak/mumble-web-proxy
    restart: unless-stopped
    ports:
      - 127.0.0.1:64737:64737
  mumble-discord-bridge:
    image: ghcr.io/ekremparlak/mumble-discord-bridge
    restart: unless-stopped
    environment:
      - MUMBLE_ADDRESS=murmur
      - MUMBLE_INSECURE=true
      - DISCORD_TOKEN=token
      - DISCORD_GID=gid
      - DISCORD_CID=cid
volumes:
  murmur_data:
