name: Docker Image CI

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [murmur_update]


jobs:

  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v2

    - name: Build murmur
      run: | 
        docker build murmur -f murmur/Dockerfile \
        --tag ghcr.io/$GITHUB_ACTOR/murmur:1.3 \
        --tag ghcr.io/$GITHUB_ACTOR/murmur:latest

    - name: Build mumble-web
      run: | 
        docker build mumble-web -f mumble-web/Dockerfile \
        --tag ghcr.io/$GITHUB_ACTOR/mumble-web:latest

    - name: Build mumble-web-proxy
      run: | 
        docker build mumble-web-proxy -f mumble-web-proxy/Dockerfile \
        --tag ghcr.io/$GITHUB_ACTOR/mumble-web-proxy:latest

    - name: Docker login
      run: >-
        echo "${{ secrets.GITHUB_TOKEN }}"
        | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
      
    - name: Push image to GitHub
      run: |
        docker push ghcr.io/$GITHUB_ACTOR/murmur:1.3
        docker push ghcr.io/$GITHUB_ACTOR/murmur:latest
        docker push ghcr.io/$GITHUB_ACTOR/mumble-web-proxy:latest
        docker push ghcr.io/$GITHUB_ACTOR/mumble-web:latest

